# restart server after each change

# to deploy on gh-pages
# url: danieloberbillig.github.io
url: "https://danieloberbillig.github.io/atha-website/"
baseurl: /atha-website
# Use baseurl when your site doesn’t sit at domain root

collections:
  authors:
    output: false

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "survey-report"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-pwa-plugin
  - jekyll-sitemap

jekyll_analytics:
  GoogleAnalytics:
    id: UA-110871482-4
    anonymizeIp: false

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html