# restart server after each change

# to deploy on gh-pages
# url: danieloberbillig.github.io
baseurl: /atha-website
# Use baseurl when your site doesn’t sit at domain root

collections:
  authors:
    output: false

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "survey-report"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-110871482-4
    anonymizeIp: false